### ISSUE TITLE
Change theme page width?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#119]
Some docs could benefit from using more screen space, see, e.g., screenshot:
![screenshot-2023-12-14T11:57:46](https://github.com/scipp/copier_template/assets/12912489/e394b0fb-51b7-4232-9ff8-d8d9bfabf357)

This can apparently be adjusted in the theme: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#horizontal-spacing. Should we make a global change to 100%, or does this hurt readability?

**Comment by SimonHeybrock** [comment]
> I think the current graph layout just doesn't scale the way we need it to.

I disagree: If we more than double the width this would be *way* more readable. Does it solve all problems? No. Would it make it somewhat usable? I think so.

**Comment by YooSunYoung** [comment]
I agree. If it makes text less readable, we can just add more line breakers, `<br>`, no...?

**Comment by SimonHeybrock** [comment]
Users can change their width of their browser window?

**Comment by jl-wynen** [comment]
> I agree. If it makes text less readable, we can just add more line breakers, `<br>`, no...?

No, this way, we couldn't rely on automatic line wrapping which currently adjusts the lines to the browser window.

> I disagree: If we more than double the width this would be way more readable. Does it solve all problems? No. Would it make it somewhat usable? I think so.

Yes, it would help. But it seems to me like it just kicks the can down the road.

**Comment by SimonHeybrock** [comment]
> > I disagree: If we more than double the width this would be way more readable. Does it solve all problems? No. Would it make it somewhat usable? I think so.
> 
> Yes, it would help. But it seems to me like it just kicks the can down the road.

I would argue that even if you implement zooming or anything fancy, any non-trivial graph will be unreadable with the current width. Therefore: Not kicking anything down the road, I feel this is required regardless of solving related issues of graph display.

**Comment by nvaytet** [comment]
I agree with @jl-wynen that very long lines of text are more difficult to read than thicker paragraphs.

I have a feeling that people working on the theme have thought very long and hard about these kind of issues (also so it works on different platforms such as tablets or phones), and it is highly likely that any attempt at changing this will probably make it worse rather than better? They have probably thought about how to make it look harmonious with plots etc...

I think that changing the width for all our docs because we don't have a good solution for the graphs is maybe trying to tackle the problem the wrong way? Right now, I'm fine with right-clicking and opening the graph into a new tab to look at it better.

**Comment by SimonHeybrock** [comment]
After reverting a problematic change in Sciline this is no longer a major issue.
